### ISSUE TITLE
Extractor does not stop when a batch is cancelled via Pyrog app

### ISSUE THREAD

**Issue by elsiehoffet-94** [arkhn/pyrog#488]
## Description
Batch is canceled, but the extraction does not stop, when using the stop batch feature of pyrog. 

## Additional context
I don't know if this is related , but this error also showed up 
```
Traceback (most recent call last):
  File "/srv/django/common/kafka/producer.py", line 59, in produce_event
    self.producer.produce(
cimpl.KafkaException: KafkaError{code=_UNKNOWN_TOPIC,val=-188,str="Unable to produce message: Local: Unknown topic"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/venv/lib/python3.8/site-packages/fluent/sender.py", line 90, in emit_with_time
    bytes_ = self._make_packet(label, timestamp, data)
  File "/srv/venv/lib/python3.8/site-packages/fluent/sender.py", line 133, in _make_packet
    return msgpack.packb(packet, **self.msgpack_kwargs)
  File "/srv/venv/lib/python3.8/site-packages/msgpack/__init__.py", line 46, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 284, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 290, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 287, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 263, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 234, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 281, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'KafkaException' object
```

**Comment by tevariou** [comment]
@elsiehoffet-94 where does this error occurs ? In the extractor ? If so, it's telling us that the extractor can't produce anymore and that the batch has been correctly stopped. It seems there's something wrong with how we handle the exception but it's a logging issue.
